### ISSUE TITLE
Readme, edit Info

### ISSUE THREAD

**Issue by schlachtkreuzer6** [ryck/MMM-DHT-Sensor#1]
Not really an Issue ;)
The GPIO Pin is not the hardware pin, its the GPIO Number so if you connect the Sensor on hardware pin 7 its GPIO 4. Therefore you need to set: sensorPin: "4" Would be good to change the Readme with an Info about that ;)

The module is nice!!

**Comment by ryck** [comment]
I added some info on the readme. Thanks!
