### ISSUE TITLE
No Data Returned after ... x Min 

### ISSUE THREAD

**Issue by Egalistel** [ryck/MMM-DHT-Sensor#20]
hello, I'm coming to you a bit to see if someone could give me some information, because I have installed a DHT11 module and the return is rather random, sometimes I see the temperature, and sometimes I get the message: no data returned

I copied the module code to the same, changing only 22 to 11 for the module.

Does anyone have any idea of ​​the cause?

In addition the temperature or the humidity rate is always a round value, 26 ° - 29% I never have a comma behind.

Thanking you in advance, sorry for the English but I only speak French.
![Capture d’écran 2021-03-03 232012](https://user-images.githubusercontent.com/61868339/109880366-1fb77000-7c77-11eb-8213-bfbaec9e8a16.png)
![Capture d’écran 2021-03-03 232040](https://user-images.githubusercontent.com/61868339/109880368-20500680-7c77-11eb-83d6-04bdf7923ed6.png)

**Comment by ryck** [comment]
@Egalistel I fixed a lot of rounding issues on the last version, can you give it a go (if you are still using it after +2 years)
