### ISSUE TITLE
Narrow temperature band

### ISSUE THREAD

**Issue by sherwood65633** [ryck/MMM-DHT-Sensor#27]
I seem to only get a temperature change of about 2+/- degree..using heat source and compressed air. The sensor IS reading and does change. but not as expected. Any ideas?

**Comment by ryck** [comment]
No idea, tbh... I just use the value the sensor/library are getting, so I don't know much about the internals... Have you tried with other sensor? Maybe that one if broken?

FWIW, I get more than +/- 2 degrees variations...
