### ISSUE TITLE
Not displaying values

### ISSUE THREAD

**Issue by mmonstudies** [ryck/MMM-DHT-Sensor#31]
HI sorry for newbie question, I was looking for similar issues posted here but apparently could not find solution for my problem.
I downloaded the latest library cm2835-1.71 which should support RPI 4B.
The node dht sensor is installed as well. I thought that the sensor could be broken but works fine with python code found on web.
[](url)
![room tempearture and humidty](https://user-images.githubusercontent.com/122314360/211402971-01d96d0e-4c0b-4dc9-b7c7-429a0f140df3.png)
What I have change is below: 
` 		{
			module: "MMM-DHT-Sensor",
			position: "top_right",
			classes: "pageL1",
			header: "Room Temperature & Humidity",
			config: {
				sensorPin: 3,
				sensorType: 11,
				updateInterval: 60 * 60 * 1000,
				initialLoadDelay: 0,
				animationSpeed: 1000,
				units: "metric",
				relativeScale: 35,
				debug: false
			}
		},
		
`
Thank you for your work and answer in advance!

**Comment by ryck** [comment]
1. Can you get data back from the python code?
2. is the pin the right one?
3. is the sensor type correct?

The module is just a fancy wrapper, so if it works in python it should work in the module...

**Comment by mmonstudies** [comment]
HI
1. Yes the pyhon code shows the temperature in console, if you are asking if I can get data from python code itno module I do not know how to implement it. 
2. Accordingly to the wiringPI it is pin number 3 which is 8th pin on left side holding the PI with ports towards a user.
3. The senosor I am using is the blue one, DHT11.

Apparently after posting here I found a message in terminal while starting magic mirror(see below)
![image](https://user-images.githubusercontent.com/122314360/211795114-8e6886d0-aeae-4e2a-ab60-6f314d70eb4b.png)
Seems that driver cannot be used, could you recommend solution?

**Comment by ryck** [comment]
Can you try to see if you are getting the temperature using this? https://learn.adafruit.com/dht-humidity-sensing-on-raspberry-pi-with-gdocs-logging/python-setup

**Comment by mmonstudies** [comment]
Hi these are the libraries which I have used previously to check the sensor.
Apparently something is going on since while executing the code from the link in terminal I get a message as below:
![image](https://user-images.githubusercontent.com/122314360/212119367-2a7ebe81-d985-42dd-8d45-d2baf64d9c91.png)
Furthermore if I execute the code from Geany it seems to be working:
![DHT test outside terminal](https://user-images.githubusercontent.com/122314360/212120317-96120470-c7b5-4f55-bcdf-1e92563f37df.png)
For comparison the code I used earliler:
![image](https://user-images.githubusercontent.com/122314360/212120856-abc1abc5-f85f-4046-b412-103ae93f384c.png)and executed in terminal:
![image](https://user-images.githubusercontent.com/122314360/212121350-9d095c84-9d95-453c-ac3d-5e6db31ee09a.png)
Frankly speaking I do not know what is wrong..

**Comment by ryck** [comment]
I don't know either, tbh... The sensor clearly works, but for some reason node is not getting the data...
Maybe you can go one level down and try to use the node-dht-sensor lib directly: https://github.com/momenso/node-dht-sensor/tree/master/examples

**Comment by mmonstudies** [comment]
Okey problem solved, went there and worked right away...
