### ISSUE TITLE
it is showing "no data returned"

### ISSUE THREAD

**Issue by petitemuse** [ryck/MMM-DHT-Sensor#5]
Hello I am totally new in this and I am trying to get the sensor DHT22 working with my MM

in MM I get the message " No data returned"
maybe the pin is not right but:

pi@raspberrypi:~/MagicMirror/modules/MMM-DHT22 $ sudo ./dht_var
usage: ./dht_var <pin> (<tries>)
description: pin is the wiringPi pin number
using 2 (GPIO 27)

{
	module: "MMM-DHT-Sensor",
	position: "top_right",
	header: "Upstairs",
	config: {
		sensorPin: 2,
		sensorType: 22,	
		updateInterval: 60 * 60 * 1000,
		initialLoadDelay: 0,
		animationSpeed: 1000,
		units: "metric",
		relativeScale: 35,
		debug: false
	}
},

what should I do?

Thank you for you help!

**Comment by petitemuse** [comment]
sorry Finally it worked!! on pin 4 !!!!

but my Mirror breaks down!

**Comment by petitemuse** [comment]
well ...
after showing me temp and hum it still does show No data returned 

I think it is when it update after an hour.

Any idea?

**Comment by jamefog** [comment]
Bonjour
Tout nouveau avec mon MagisMirror, j'essaye de cloner le Module  MMM-DHT-sensor mais au bebut du clonage on me demande mon Username Github: et le password où les trouver, j'ai installé plusieurs autres modules et lors des clonage on me demandait le mot de pass Sudo c'est tout
Merci de votre aide
