### ISSUE TITLE
Does not show icons and header

### ISSUE THREAD

**Issue by Bursucel** [ryck/MMM-DHT-Sensor#6]
I am running the module on two MagicMirror versions. On the older ( i think it is 2.6.0) works fine, on the newest version 2.7.1 the header and the icons do not show. I’ve read about issues with FontAwesome on the newest version and did all the fixes I could find. I am stuck.
Any other ideas I could try?
I get the sensor readings.
Thanks

**Comment by upupdown42** [comment]
Hi, same problem here. The header-info with divider-bar is not displayed either, and Ryck's other module "MMM-AQI" has the same problem. Some messed up CSS?
Thanks and best regards

**Comment by shakil10vr** [comment]
To solve the header,
change in  MMM-DHT-Sensor.js.
replace
```
getHeader: function() {
    return this.config.header;
  },
```
with
```
getHeader: function() {
    return this.data.header;
  },
```

**Comment by upupdown42** [comment]
Thank you shakil10vr!

**Comment by upupdown42** [comment]
To solve the icon problem, I replaced in MMM-DHT.css
```
.data:before {
  font-family: 'FontAwesome';
}
```

with 
```
.data:before {
  font-family: 'weathericons';
}
```

and then all the thermometers are f055: 
```
.temperature:before {
  content: '\f055';
}
```
and the humidity is f07a:
```
.humidity:before {
  content: '\f07a';
}
```

worked for me. Cheers

**Comment by Bursucel** [comment]
Thank you both  shakil10vr and upupdown42. Both fixes worked for me. Your help is much appreciated.

**Comment by ryck** [comment]
I just pushed a new version that fixes both issues.
Thanks to everybody for the proposed solutions, and sorry about the delay!
