### ISSUE TITLE
icon issues

### ISSUE THREAD

**Issue by CaptainFlam27** [ryck/MMM-DHT-Sensor#7]
Hi,

I installed the DHT-Sensor module today, it works fine with my sensor but I do have an issue with the icons : none is showing for the temp reading, and a simple square is showing for the humidity reading. 

I believe this is linked to troubles with the Font Awesome, but as I'm fairly new to this and because a fix was released not so long ago, I do not want to mess with the files. 
I may have missed something while installing the module, the one thing bothering me though is that the behaviour is different for the temp and humidity lines : should it only be a font issue, I should see squares on both lines.

Does anyone have by any chance an idea to fix this problem ?

Thank you

**Comment by ryck** [comment]
Try to update both MM and the module to the latest versions
