### ISSUE TITLE
Fix for rounding...

### ISSUE THREAD

**Issue by BKeyport** [ryck/MMM-DHT-Sensor#8]
I've forked off and added rounding to the module. I plan to also add "both" as a temperature display option (got the room, might as well use it).

In Imperial mode, it'll sometimes display as "XX.99999999999999" or "XX.000000000001" 

I've added a Math.round() function around the temperature calculations to fix it in my fork. 

I don't know how to automate the request to merge, so feel free to look at my mod...

http://github.com/BKeyport/MMM-DHT-Sensor

**Comment by ryck** [comment]
I merged your PR (thanks!) but then I found some issues regarding rounding. You can have a look on the commit history, maybe you want to implement something similar...
